---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ= #Add Timezone
    volumes:
      - ./config:/config
      - /Path/to/data/:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr_suite

networks:
  arr_suite:
    external: true
