services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: '192.168.1.149' #update, assign open ip manually
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: '' # update according to your timezone
      WEBPASSWORD: 'password' #update password
    volumes:
      - './etc-pihole:/etc/pihole' #update
      - './etc-dnsmasq.d:/etc/dnsmasq.d' #update
    restart: always

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enp3s0 # eth0 will need to be replaced by name of your ethernet network interface
    ipam:
      config:
        - subnet: 192.168.1.0/24 #update if needed
          gateway: 192.168.1.1 #update if needed

