services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: "watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Dhaka
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=false
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 30 14 * * sat 
    restart: no
